### PR TITLE
Create backup jobs

### LINKED ISSUE #8: Setup CKAN DB backup job
Setup a regular database backup job for CKAN

Tasks:
- [x] Run job regularly (daily)
- [x] Dump Postgres data ([documentation](https://docs.ckan.org/en/2.9/maintaining/database-management.html))
- [x] Dump Solr data
- [ ] Dump other data systems (if relevant)
- [x] Store dump on S3

### LINKED ISSUE #9: Setup Keycloak Backup job
Backup Keycloak

### PR DESCRIPTION
**Pull request by vikig07**

### CODE REVIEW

**Review by akafazov — APPROVED** [review]
LGTM

**Comment by vikig07** [comment]
@akafazov Since the last review backups of Keycloak and Solr have been added. The job has now been running for almost a month and there are entries for each day in the GCP bucket, I also checked the logs and there hasn't been any issue. Should I add a check that will delete older dumps after a certain amount of time, so they don't become too many?

**Comment by akafazov** [comment]
> so checked the logs and there hasn't been any iss

I also checked, backups are there. What is the retention period? 1 Month looks like to short of a time.

**Comment by vikig07** [comment]
> What is the retention period?

Currently there's no retention policy set on the bucket.

**Comment by akafazov** [comment]
> > What is the retention period?
> 
> Currently there's no retention policy set on the bucket.

How many backups do we keep? Do we delete older ones?

**Comment by vikig07** [comment]
> > > What is the retention period?
> > 
> > 
> > Currently there's no retention policy set on the bucket.
> 
> How many backups do we keep? Do we delete older ones?

We don't delete the older ones. Right now every backup made since the job was created is kept. They're close to 30 for each separate DB.

**Review by akafazov — APPROVED** [review]

**Pull request merged**
